baseURL = 'https://blog.cloudprog.org/'
languageCode = 'en-us'
title = 'My Blog at cloudprog.org'
theme = 'ananke'

[params.ananke.social.linkedin]
username = "permadsenaalborg"

[params.ananke.social.bluesky]
username = "permadsenaalborg.bsky.social"