baseURL = 'https://blog.cloudprog.org/'
languageCode = 'en-us'
title = 'My Blog at cloudprog.org'
theme = 'ananke'



[params.ananke.social.share]
networks = [
  "email",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "bluesky",
  "linkedin"
]

[params]
email = "per.madsen.aalborg@gmail.com"

[params.ananke.social.email]
email = "per.madsen.aalborg@gmail.com"

[params.ananke.social.linkedin]
username = "per-madsen-aalborg"

[params.ananke.social.bluesky]
username = "permadsenaalborg.bsky.social"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3