baseURL = 'https://blog.cloudprog.org/'
languageCode = 'en-us'
title = 'My Blog at cloudprog.org'
theme = 'ananke'



[params.ananke.social.share]
networks = [
  "email",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "bluesky",
  "linkedin"
]

[params.ananke.social.linkedin]
username = "per-madsen-aalborg"

[params.ananke.social.bluesky]
username = "permadsenaalborg.bsky.social"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
