name: Build site inside hugo container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      pages: write
    container: ghcr.io/permadsenaalborg2/publicnotes:main
    steps:
      - run: echo "running inside container"

      - uses: actions/checkout@v3

      - run: chmod +x ./hugo.sh
      - run: ls -ls

      - run: ./hugo.sh

      - uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: blog/public/

      - uses: actions/deploy-pages@v4

