name: Build site inside hugo container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/permadsenaalborg2/publicnotes:main
    steps:
      - run: echo "running inside container"

      - uses: actions/checkout@v3

      - run: chmod +x ./hugo.sh
      - run: ls -ls

      - run: ./hugo.sh
